name: glowmind
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  fl_chart: ^0.66.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  supabase_flutter: '>=1.10.0'
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/sleep/
    - assets/audio/study/
    - assets/audio/party/
    - assets/audio/meditate/
    - assets/audio/focus/
    - assets/audio/nature/
    - assets/curated_sound_playlists.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
